version: '3'

services:
  db_postgres:
    image: postgres:14.3
    container_name: psql14
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ${POSTGRES_VOLUMES_DATA}:/var/lib/postgresql/data

  db_redis:
    image: redis:7
    container_name: redis7
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${REDIS_VOLUMES_DATA}:/data
    command: /bin/bash -c "redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes"
